// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AppMenu: typeof import('./src/components/AppMenu.vue')['default']
    CommonFooter: typeof import('./src/components/common/Footer.vue')['default']
    ElMenu: typeof import('element-plus/lib')['ElMenu']
    ElMenuItem: typeof import('element-plus/lib')['ElMenuItem']
    ElSubMenu: typeof import('element-plus/lib')['ElSubMenu']
    IconCarbonCampsite: typeof import('~icons/carbon/campsite')['default']
    IconCarbonDicomOverlay: typeof import('~icons/carbon/dicom-overlay')['default']
    IconCarbonHome: typeof import('~icons/carbon/home')['default']
    IconCarbonVirtualPrivateCloud: typeof import('~icons/carbon/virtual-private-cloud')['default']
    IconCarbonWarning: typeof import('~icons/carbon/warning')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    UtilsRaw: typeof import('./src/components/utils/Raw.vue')['default']
  }
}
