// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    CommonFooter: typeof import('./../src/components/common/Footer.vue')['default']
    ElAvatar: typeof import('element-plus/lib')['ElAvatar']
    ElContainer: typeof import('element-plus/lib')['ElContainer']
    ElDialog: typeof import('element-plus/lib')['ElDialog']
    ElFooter: typeof import('element-plus/lib')['ElFooter']
    ElHeader: typeof import('element-plus/lib')['ElHeader']
    ElMain: typeof import('element-plus/lib')['ElMain']
    ElMenu: typeof import('element-plus/lib')['ElMenu']
    ElMenuItem: typeof import('element-plus/lib')['ElMenuItem']
    ElRadioButton: typeof import('element-plus/lib')['ElRadioButton']
    ElRadioGroup: typeof import('element-plus/lib')['ElRadioGroup']
    ElSubMenu: typeof import('element-plus/lib')['ElSubMenu']
    HeadMenu: typeof import('./../src/components/head/Menu.vue')['default']
    HeadTimer: typeof import('./../src/components/head/Timer.vue')['default']
    HeadToolbar: typeof import('./../src/components/head/Toolbar.vue')['default']
    HeadUserPanel: typeof import('./../src/components/head/UserPanel/index.vue')['default']
    HeadUserPanelDialog: typeof import('./../src/components/head/UserPanel/Dialog.vue')['default']
    HeadUserPanelInfo: typeof import('./../src/components/head/UserPanel/Info.vue')['default']
    HeadUserPanelLogin: typeof import('./../src/components/head/UserPanel/Login.vue')['default']
    HeadUserPanelProviderLinks: typeof import('./../src/components/head/UserPanel/ProviderLinks.vue')['default']
    IconCarbonCampsite: typeof import('~icons/carbon/campsite')['default']
    IconCarbonDicomOverlay: typeof import('~icons/carbon/dicom-overlay')['default']
    IconCarbonHome: typeof import('~icons/carbon/home')['default']
    IconCarbonLicenseGlobal: typeof import('~icons/carbon/license-global')['default']
    IconCarbonLogin: typeof import('~icons/carbon/login')['default']
    IconCarbonLogout: typeof import('~icons/carbon/logout')['default']
    IconCarbonVirtualPrivateCloud: typeof import('~icons/carbon/virtual-private-cloud')['default']
    IconCarbonWarning: typeof import('~icons/carbon/warning')['default']
    IconCibGithub: typeof import('~icons/cib/github')['default']
    IconCibGoogle: typeof import('~icons/cib/google')['default']
    IconCibYandex: typeof import('~icons/cib/yandex')['default']
    Raw: typeof import('./../src/components/Raw.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
